const PRODUCT_DATA = {
  fruits_vegetables: {
    id: 1,
    title: 'Fruits and Vegetables',
    routeName: 'fruits_vegetables',
    items: {
      banana: {
        id: 1,
        name: 'Banana',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/27270000/muz-yerli-kg-9d3d01',
        price: 1.1,
        discount: 0.15,
        unit: 'Kg',
        path: 'fruits_vegetables/banana'
      },
      avacado: {
        id: 2,
        name: 'Avacado',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/28010004/28010004-10a053',
        price: 1.2,
        discount: 0.3,
        unit: 'Piece',
        path: 'fruits_vegetables/avacado'
      },
      mango: {
        id: 3,
        name: 'Mango',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/27580003/mango-adet-604864',
        price: 1.5,
        discount: 0.2,
        unit: 'Piece',
        path: 'fruits_vegetables/mango'
      },
      onion: {
        id: 4,
        name: 'Onion',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/28420000/sogan-kuru-dokme-kg-25131e',
        price: 0.5,
        discount: 0.1,
        unit: 'Kg',
        path: 'fruits_vegetables/onion'
      },
      tomato: {
        id: 5,
        name: 'Tomato',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/28080000/domates-kg-c7462d',
        price: 0.82,
        discount: 0,
        unit: 'Kg',
        path: 'fruits_vegetables/tomato'
      },
      aubergine: {
        id: 6,
        name: 'Aubergine',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/28303000/patlican-kemer-kg-2ac52c',
        price: 1.2,
        discount: 0,
        unit: 'Kg',
        path: 'fruits_vegetables/aubergine'
      },
      zucchini: {
        id: 7,
        name: 'Zucchini',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/28160000/kabak-sakiz-kg-31919c',
        price: 1.3,
        discount: 0.20,
        unit: 'Kg',
        path: 'fruits_vegetables/zucchini'
      },
      paprika: {
        id: 8,
        name: 'Paprika',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/28053000/biber-kirmizi-kg-4ad206',
        price: 0.9,
        discount: 0,
        unit: 'Kg',
        path: 'fruits_vegetables/paprika'
      },
      grapefruit: {
        id: 9,
        name: 'Grapefruit',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/27161000/greyfurt-kg-96423c',
        price: 1.2,
        discount: 0,
        unit: 'Kg',
        path: 'fruits_vegetables/grapefruit'
      },
      lemon: {
        id: 10,
        name: 'Lemon',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/27260002/limon-kg-fbc52a',
        price: 0.3,
        discount: 0,
        unit: 'Piece',
        path: 'fruits_vegetables/lemon'
      },
      appel_granny: {
        id: 11,
        name: 'Appel Granny',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/27133000/elma-granny-smith-kg-0e9183',
        price: 0.8,
        discount: 0,
        unit: 'Kg',
        path: 'fruits_vegetables/appel_granny'
      },
      pear: {
        id: 12,
        name: 'Pear',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/27023000/armut-ankara-kg-b3f795',
        price: 0.9,
        discount: 0,
        unit: 'Kg',
        path: 'fruits_vegetables/pear'
      },
      quince: {
        id: 13,
        name: 'Quince',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/27030000/ayva-kg-6ac82d',
        price: 1.3,
        discount: 0,
        unit: 'Kg',
        path: 'fruits_vegetables/quince'
      },
      carrot: {
        id: 14,
        name: 'Carrot',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/28129037/havuc-beypazari-paket-kg-b3accf',
        price: 0.6,
        discount: 0,
        unit: 'Piece',
        path: 'fruits_vegetables/carrot'
      },
      kiwi: {
        id: 15,
        name: 'Kiwi',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/27251234/dogu-karadeniz-kivisi-kg-8d9fb6',
        price: 1.9,
        discount: 0,
        unit: 'Kg',
        path: 'fruits_vegetables/kiwi'
      },
      pineapple: {
        id: 16,
        name: 'pineapple',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/27501003/-ananas-adet-c1fa49',
        price: 1.4,
        discount: 0,
        unit: 'Piece',
        path: 'fruits_vegetables/pineapple'
      },
      strawberry: {
        id: 17,
        name: 'Strawberry',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/27081000/27081000-7e292e',
        price: 4.5,
        discount: 0,
        unit: 'Kg',
        path: 'fruits_vegetables/strawberry'
      },
      mandarin: {
        id: 18,
        name: 'Mandarin',
        brand: 'Bizden',
        title: 'Fruits and Vegetables',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/27286003/27286003-49e7ca',
        price: 1.4,
        discount: 0,
        unit: 'Kg',
        path: 'fruits_vegetables/mandarin'
      },
    }
  },
  meat_chicken_fish: {
    id: 2,
    title: 'Meat, Chicken and Fish',
    routeName: 'meat_chicken_fish',
    items: {
      pinar_illaki_dana_sucuk: {
        id: 19,
        name: 'Pınar İllaki Dana Sucuk 240 G',
        brand: 'Pinar',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/14209433/14209433-7957ed',
        price: 4.6,
        discount: 0.1,
        unit: 'Piece',
        path: 'meat_chicken_fish/pinar_illaki_dana_sucuk'
      },
      beef_lamb_chop: {
        id: 20,
        name: 'Beef Lamb Chop',
        brand: 'Pinar',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/25010560/25010560-9a64ab',
        price: 4.5,
        discount: 0.2,
        unit: 'Kg',
        path: 'meat_chicken_fish/beef_lamb_chop'
      },
      specialist_butcher_beef_cubes: {
        id: 21,
        name: 'Specialist Butcher Beef Cubes',
        brand: 'Pinar',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/25509037/25509037-b43982',
        price: 4.7,
        discount: 0,
        unit: 'Kg',
        path: 'meat_chicken_fish/specialist_butcher_beef_cubes'
      },
      bolez_köylüm_half_chicken: {
        id: 22,
        name: 'Bolez Köylüm Half Chicken',
        brand: 'Bolez',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/13019530/13019530-31347f',
        price: 2.1,
        discount: 0,
        unit: 'Kg',
        path: 'meat_chicken_fish/bolez_köylüm_half_chicken'
      },
      bolez_köylüm_tenderloin: {
        id: 23,
        name: 'Bolez Köylüm Tenderloin',
        brand: 'Bolez',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/13019505/13019505-a0b79e',
        price: 3.2,
        discount: 0,
        unit: 'Kg',
        path: 'meat_chicken_fish/bolez_köylüm_tenderloin'
      },
      banvit_chicken_grill: {
        id: 24,
        name: 'Banvit Chicken Grill',
        brand: 'Banvit',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/46040101/46040101-dacafe',
        price: 3.6,
        discount: 0,
        unit: 'Kg',
        path: 'meat_chicken_fish/banvit_chicken_grill'
      },
      banvit_chicken_nugget_700_G: {
        id: 25,
        name: 'Banvit Chicken Nugget 700 G',
        brand: 'Banvit',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/46040053/46040053-497568',
        price: 1.1,
        discount: 0,
        unit: 'Piece',
        path: 'meat_chicken_fish/banvit_chicken_nugget_700_G'
      },
      beypilic_plate_leg_chops: {
        id: 26,
        name: 'Beypiliç Plate Leg Chops',
        brand: 'Beypiliç',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/13019037/13019037-a8dc7d',
        price: 1.9,
        discount: 0,
        unit: 'Kg',
        path: 'meat_chicken_fish/beypilic_plate_leg_chops'
      },
      bolez_köylüm_chicken: {
        id: 27,
        name: 'Bolez Köylüm Chicken',
        brand: 'Bolez',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/13019530/13019530-31347f',
        price: 3.1,
        discount: 0,
        unit: 'Kg',
        path: 'meat_chicken_fish/bolez_köylüm_chicken'
      },
      bolez_tenderloin: {
        id: 28,
        name: 'Bolez Tenderloin',
        brand: 'Bolez',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/13019505/13019505-a0b79e',
        price: 3.1,
        discount: 0,
        unit: 'Kg',
        path: 'meat_chicken_fish/bolez_tenderloin'
      },
      banvit_grill: {
        id: 29,
        name: 'Banvit Grill',
        brand: 'Banvit',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/46040101/46040101-dacafe',
        price: 3.5,
        discount: 0,
        unit: 'Kg',
        path: 'meat_chicken_fish/banvit_grill'
      },
      banvit_chicken: {
        id: 30,
        name: 'Banvit Chicken',
        brand: 'Banvit',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/46040053/46040053-497568',
        price: 1.2,
        discount: 0,
        unit: 'Piece',
        path: 'meat_chicken_fish/banvit_chicken'
      },
      beypilic_plate_chops: {
        id: 31,
        name: 'Beypiliç Plate Chops',
        brand: 'Beypiliç',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/13019037/13019037-a8dc7d',
        price: 1.4,
        discount: 0,
        unit: 'Kg',
        path: 'meat_chicken_fish/beypilic_plate_chops'
      },
      polonez_salami: {
        id: 32,
        name: 'Polonez Salami',
        brand: 'Polonez',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/14109223/polonez-macar-salam-kg-cb43dd',
        price: 8,
        discount: 0,
        unit: 'Kg',
        path: 'meat_chicken_fish/polonez_salami'
      },
      polonez_roasting: {
        id: 33,
        name: 'Polonez Roasting',
        brand: 'Polonez',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/14401502/14401502-2ad4b6',
        price: 5,
        discount: 0,
        unit: 'Piece',
        path: 'meat_chicken_fish/polonez_roasting'
      },
      dardanel_mussel_meat: {
        id: 34,
        name: 'Dardanel Mussel Meat',
        brand: 'Dardanel',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/17501041/17501041-6bbd78',
        price: 3.5,
        discount: 0,
        unit: 'Piece',
        path: 'meat_chicken_fish/dardanel_mussel_meat'
      },
      dardanel_salmon: {
        id: 35,
        name: 'Dardanel Salmon',
        brand: 'Dardanel',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/17501038/17501038-83fb91',
        price: 5.4,
        discount: 0,
        unit: 'Piece',
        path: 'meat_chicken_fish/dardanel_salmon'
      },
      polonez_turkey_salami: {
        id: 36,
        name: 'Polonez Turkey Salami',
        brand: 'Polonez',
        title: 'Meat, Chicken and Fish',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/14109162/14109162-e8af3a',
        price: 4.2,
        discount: 0,
        unit: 'Piece',
        path: 'meat_chicken_fish/polonez_turkey_salami'
      }
    }
  },
  milk_breakfast:{
    id: 3,
    title: 'Milk and Breakfast',
    routeName: 'milk_breakfast',
    items: {
      taciroglu_kasgaval_cheese: {
        id: 37,
        name: 'Taciroglu Kasgaval Cheese',
        brand: 'Taciroglu',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/10403145/taciroglu-kaskaval-peyniri-kg-ef5184',
        price: 5.1,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/taciroglu_kasgaval_cheese'
      },
      sütBon_goat_cheese: {
        id: 38,
        name: 'SütBon Goat Cheese',
        brand: 'SütBon',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/10019163/10019163-8573d9',
        price: 7.8,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/sütBon_goat_cheese'
      },
      bahcivan_white_cheese:{
        id: 39,
        name: 'Bahcivan White Cheese',
        brand: 'Bahcivan',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/10019208/10019208-4fb9f4',
        price: 4.7,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/bahcivan_white_cheese'
      },
      akpinar_tulum_cheese:{
        id: 40,
        name: 'Akpinar Tulum Cheese',
        brand: 'Akpinar',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/10202003/akpinar-t-y-olgunlastirilmis-tulum-peyniri-kg-cec091',
        price: 6.1,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/akpinar_tulum_cheese'
      },
      akpinar_old_yellow_cheese:{
        id: 41,
        name: 'Akpinar Old Yellow Cheese',
        brand: 'Akpinar',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/10108663/akpinar-tam-yagli-eski-kasar-peyniri-kg-ec8bfa',
        price: 7.1,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/akpinar_old_yellow_cheese'
      },
      egg_20x:{
        id: 42,
        name: '20x Egg',
        brand: 'Bahcivan',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/20001992/20001992-f01488',
        price: 3.1,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/egg_20x'
      },
      egg_10x:{
        id: 43,
        name: '10x Egg',
        brand: 'Bahcivan',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/20001994/20001994-1e60db',
        price: 1.7,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/egg_10x'
      },
      egg_30x:{
        id: 44,
        name: '30x Egg',
        brand: 'Bahcivan',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/20001976/20001976-2e0cb2',
        price: 3.7,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/egg_30x'
      },
      ilyada_black_olives:{
        id: 45,
        name: 'Ilyada Black Olives',
        brand: 'Ilyada',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/16011965/16011965-596691',
        price: 3.5,
        discount: 0,
        unit: 'Kg',
        path: 'milk_breakfast/ilyada_black_olives'
      },
      fora_olives_paste:{
        id: 46,
        name: 'Fora Olives Paste',
        brand: 'Fora',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/16011941/fora-sade-siyah-zeytin-ezmesi-340-gr-261087',
        price: 1.1,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/fora_olives_paste'
      },
      whole_green_olives_400G:{
        id: 47,
        name: 'Whole Green Olives 400G',
        brand: 'Oncü',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/16020236/16020236-31c5ee',
        price: 2.4,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/whole_green_olives_400G'
      },
      oncü_black_olives_1000G:{
        id: 48,
        name: 'Oncü Black Olives 1000G',
        brand: 'Oncü',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/16011995/16011995-6a8fe2',
        price: 6.5,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/oncü_black_olives_1000G'
      },
      balparmak_honig_mix_180G:{
        id: 49,
        name: 'Balparmak Honig Mix 180G',
        brand: 'Balparmak',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/07209847/07209847-8c5235',
        price: 2.2,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/balparmak_honig_mix_180G'
      },
      koska_kürek_halvah_350G:{
        id: 50,
        name: 'Koska Kürek Halvah 350G',
        brand: 'Koska',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/07081988/07081988-811659',
        price: 1.5,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/koska_kürek_halvah_350G'
      },
      koska_halvah_with_pistachio_350G:{
        id: 51,
        name: 'Koska Halvah with Pistachio 350G',
        brand: 'Koska',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/07081990/07081990-148999',
        price: 2.5,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/koska_halvah_with_pistachio_350G'
      },
      fomilk_milk_vegan_1Lt:{
        id: 52,
        name: 'Fomilk Milk Vegan 1Lt',
        brand: 'Fomilk ',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/11010836/11010836-861360',
        price: 0.7,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/fomilk_milk_vegan_1Lt'
      },
      sek_macchiato_330Ml:{
        id: 53,
        name: 'Sek Macchiato 330Ml',
        brand: 'Sek',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/11015687/11015687-994755',
        price: 0.47,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/sek_macchiato_330Ml'
      },
      activia_smoothie_200Ml:{
        id: 54,
        name: 'Activia Smoothie 200Ml',
        brand: 'Activia',
        title: 'Milk and Breakfast',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/11015689/11015689-7c03f4',
        price: 0.55,
        discount: 0,
        unit: 'Piece',
        path: 'milk_breakfast/activia_smoothie_200Ml'
      }
    }
  },
  food: {
    id: 4,
    title: 'Food',
    routeName: 'food',
    items: {
      Barilla_Glutensiz_Penne_Rigate_Kalem_Makarna_400_G:{
        id: 55,
        name: 'Barilla Glutensiz Penne Rigate Kalem Makarna 400 G',
        brand: 'Barilla',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05039587/05039587-699402',
        price: 1,
        discount: 0,
        unit: 'Piece',
        path: 'food/Barilla_Glutensiz_Penne_Rigate_Kalem_Makarna_400_G'
      },
      ankara_Pasta_500G:{
        id: 56,
        name: 'ankara Pasta 500G',
        brand: 'Ankara',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05030215/nuh-un-ankara-boncuk-makarna-500-gr-d86176',
        price: 0.6,
        discount: 0,
        unit: 'Piece',
        path: 'food/ankara_Pasta_500G'
      },
      Burgu_Pasta_500G:{
        id: 57,
        name: 'Burgu Pasta 500G',
        brand: 'Burgu',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05030185/05030185-188ee1',
        price: 0.4,
        discount: 0,
        unit: 'Piece',
        path: 'food/Burgu_Pasta_500G'
      },
      Pastavilla_Mezzanelli_500G:{
        id: 58,
        name: 'Pastavilla Mezzanelli 500G',
        brand: 'Pastavilla',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05030727/05030727-f018c1',
        price: 0.7,
        discount: 0,
        unit: 'Piece',
        path: 'food/Pastavilla_Mezzanelli_500G'
      },
      Veronelli_Penne_500G:{
        id: 59,
        name: 'Veronelli Penne 500G',
        brand: 'Veronelli',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05030256/05030256-87d667',
        price: 0.8,
        discount: 0,
        unit: 'Piece',
        path: 'food/Veronelli_Penne_500G'
      },
      Filiz_Kuskus_Pasta_500G:{
        id: 60,
        name: 'Filiz Kuskus Pasta 500G',
        brand: 'Filiz',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05030350/05030350-8c671a',
        price: 0.7,
        discount: 0,
        unit: 'Piece',
        path: 'food/Filiz_Kuskus_Pasta_500G'
      },
      Filiz_Spagetti_Pasta_500G:{
        id: 61,
        name: 'Filiz Spagetti Pasta 500G',
        brand: 'Filiz',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05030363/05030363-670533',
        price: 0.9,
        discount: 0,
        unit: 'Piece',
        path: 'food/Filiz_Spagetti_Pasta_500G'
      },
      Barilla_Farfalle_500G:{
        id: 62,
        name: 'Barilla Farfalle 500G',
        brand: 'Barilla',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05030347/05030347-f6feba',
        price: 1.4,
        discount: 0,
        unit: 'Piece',
        path: 'food/Barilla_Farfalle_500G'
      },
      Duru_Pilavlik_Bulgur_1000G:{
        id: 63,
        name: 'Duru Pilavlik Bulgur 1000G',
        brand: 'Duru',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/01075029/01075029-dd57e7',
        price: 1.5,
        discount: 0,
        unit: 'Piece',
        path: 'food/Duru_Pilavlik_Bulgur_1000G'
      },
      Makaroma_Tagliatelle_500_G:{
        id: 64,
        name: 'Makaroma Tagliatelle 500 G',
        brand: 'Makaroma',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05030071/05030071-564756',
        price: 1.6,
        discount: 0,
        unit: 'Piece',
        path: 'food/Makaroma_Tagliatelle_500_G'
      },
      Green_Lentil_1KG:{
        id: 65,
        name: 'Green Lentil 1KG',
        brand: 'Danem',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/01051801/01051801-7c61e6',
        price: 1.5,
        discount: 0,
        unit: 'Piece',
        path: 'food/Green_Lentil_1KG'
      },
      Danem_Rice_2KG:{
        id: 66,
        name: 'Danem Rice 2KG',
        brand: 'Danem',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/01010139/01010139-76004d',
        price: 1.8,
        discount: 0,
        unit: 'Piece',
        path: 'food/Danem_Rice_2KG'
      },
      Noba_Osmancik_Rice_1Kg:{
        id: 67,
        name: 'Noba Osmancik Rice 1 Kg',
        brand: 'Noba',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/01010020/01010020-d5cdfc',
        price: 1.5,
        discount: 0,
        unit: 'Piece',
        path: 'food/Noba_Osmancik_Rice_1Kg'
      },
      Arbella_Peynir_Soslu_Cabuk_Makarna_67_G:{
        id: 68,
        name: 'Arbella Peynir Soslu Çabuk Makarna 67 G',
        brand: 'Arbella',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05030063/05030063-49920f',
        price: 1,
        discount: 0.2,
        unit: 'Piece',
        path: 'food/Arbella_Peynir_Soslu_Cabuk_Makarna_67_G'
      },
      Torku_Bulgur_1Kg:{
        id: 69,
        name: 'Torku Bulgur 1Kg',
        brand: 'Torku',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/01089962/torku-koftelik-bulgur-1-kg-732b82',
        price: 0.72,
        discount: 0,
        unit: 'Piece',
        path: 'food/Torku_Bulgur_1Kg'
      },
      Ipek_Pilavlik_Bulgur_1Kg:{
        id: 70,
        name: 'Ipek Pilavlik Bulgur 1Kg',
        brand: 'Ipek',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/01075130/01075130-b61ff7',
        price: 0.8,
        discount: 0,
        unit: 'Piece',
        path: 'food/Ipek_Pilavlik_Bulgur_1Kg'
      },
      Yayla_Dermason_Beans_2Kg:{
        id: 71,
        name: 'Yayla Dermason Beans 2Kg',
        brand: 'Yayla',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/01020099/01020099-d4e0be',
        price: 3.9,
        discount: 0,
        unit: 'Piece',
        path: 'food/Yayla_Dermason_Beans_2Kg'
      },
      Danem_Lentil_2Kg:{
        id: 72,
        name: 'Danem Lentil 2Kg',
        brand: 'Danem',
        title: 'Food',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/01060005/01060005-ae37cf',
        price: 2.4,
        discount: 0,
        unit: 'Piece',
        path: 'food/Danem_Lentil_2Kg'
      },
    }
  },
  beverage:{
    id: 5,
    title: 'Beverage',
    routeName: 'beverage',
    items: {
      erikli_water_330ml:{
        id: 73,
        name: 'Erikli Water 330ml',
        brand: 'Erikli',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/08062200/erikli-su-dogal-kaynak-suyu-0-33-l-b5c2be',
        price: 0.2,
        discount: 0,
        unit: 'Piece',
        path: 'beverage/erikli_water_330ml'
      },
      Erikli_Water_5L:{
        id: 74,
        name: 'Erikli Water 5L',
        brand: 'Erikli',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/08062203/08062203-2f4ec4',
        price: 0.7,
        discount: 0,
        unit: 'Piece',
        path: 'beverage/Erikli_Water_5L'
      },
      Erikli_Water_500mL:{
        id: 75,
        name: 'Erikli Water 0.5L',
        brand: 'Erikli',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/08062201/08062201-3aa86b',
        price: 0.3,
        discount: 0,
        unit: 'Piece',
        path: 'beverage/Erikli_Water_500mL'
      },
      Damla_Water_330ml:{
        id: 76,
        name: 'Damla Water 330ml',
        brand: 'Damla',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/08060314/08060314-3569b1',
        price: 0.35,
        discount: 0,
        unit: 'Piece',
        path: 'beverage/Damla_Water_330ml'
      },
      Form_Cayı_40_G:{
        id: 77,
        name: 'Form Çayı 40 G',
        brand: 'Entschlackungstee',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/03132142/entschlackungstee-zayiflama-cayi-40-gr-bd27e0',
        price: 0.9,
        discount: 0.1,
        unit: 'Piece',
        path: 'beverage/Form_Cayı_40_G'
      },
      Nestle_Pure_Life_1500ml:{
        id: 78,
        name: 'Nestle Pure Life 1.5L',
        brand: 'Nestle',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/08061655/nestle-pure-life-su-1-5-l-27412d',
        price: 0.25,
        discount: 0,
        unit: 'Piece',
        path: 'beverage/Nestle_Pure_Life_1500ml'
      },
      Erikli_Su_12x500_Ml:{
        id: 79,
        name: 'Erikli Glass 750ml',
        brand: 'Erikli',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/08060028/08060028-53688c',
        price: 1.2,
        discount: 0.1,
        unit: 'Piece',
        path: 'beverage/Erikli_Su_12x500_Ml'
      },
      Hayat_Frozen_Special_330ml:{
        id: 80,
        name: 'Hayat Frozen Special 0.33L',
        brand: 'Hayat',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/08060570/08060570-e9f453',
        price: 0.17,
        discount: 0,
        unit: 'Piece',
        path: 'beverage/Hayat_Frozen_Special_330ml'
      },
      Erikli_Su_2X5_L_Avantajlı_Paket:{
        id: 81,
        name: 'Erikli Su 2X5 L Avantajlı Paket',
        brand: 'Erikli',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/08062217/08062217-22cae1',
        price: 3.1,
        discount: 0.2,
        unit: 'Piece',
        path: 'beverage/Erikli_Su_2X5_L_Avantajlı_Paket'
      },
      Tchibo_Barista_Espresso_1Kg:{
        id: 82,
        name: 'Tchibo Barista Espresso 1Kg',
        brand: 'Tchibo',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/03242957/03242957-498d22',
        price: 12.9,
        discount: 0,
        unit: 'Piece',
        path: 'beverage/Tchibo_Barista_Espresso_1Kg'
      },
      Tchibo_Türk_Kahvesi_100_G:{
        id: 83,
        name: 'Tchibo Türk Kahvesi 100 G',
        brand: 'Tchibo',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/03212075/03212075-1fc541',
        price: 2.9,
        discount: 0.1,
        unit: 'Piece',
        path: 'beverage/Tchibo_Türk_Kahvesi_100_G'
      },
      Tchibo_Gold_Selection_50G:{
        id: 84,
        name: 'Tchibo Gold Selection 50G',
        brand: 'Tchibo',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/03231566/03231566-c5cf8d',
        price: 1.7,
        discount: 0,
        unit: 'Piece',
        path: 'beverage/Tchibo_Gold_Selection_50G'
      },
      Sirma_Mandarin_6x:{
        id: 85,
        name: 'Sirma Mandarin 6x',
        brand: 'Sirma',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/08040143/08040143-0e20bf',
        price: 3.1,
        discount: 0,
        unit: 'Piece',
        path: 'beverage/Sirma_Mandarin_6x'
      },
      Tchibo_Gold_Selection_Filtre_Kahve_250_G:{
        id: 86,
        name: 'Tchibo Gold Selection Filtre Kahve 250 G',
        brand: 'Tchibo',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/03271968/03271968-436e25',
        price: 4.2,
        discount: 0.1,
        unit: 'Piece',
        path: 'beverage/Tchibo_Gold_Selection_Filtre_Kahve_250_G'
      },
      Dogus_Tee_500G:{
        id: 87,
        name: 'Dogus Tee 500G',
        brand: 'Dogus',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/03118005/dogus-rize-cay-500-gr-86f410',
        price: 2,
        discount: 0,
        unit: 'Piece',
        path: 'beverage/Dogus_Tee_500G'
      },
      Caykur_Cay_Cicegi_200G:{
        id: 88,
        name: 'Caykur Cay Cicegi 200G',
        brand: 'Caykur',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/03111309/03111309-559360',
        price: 1.6,
        discount: 0,
        unit: 'Piece',
        path: 'beverage/Caykur_Cay_Cicegi_200G'
      },
      Pinar_Kefir_Probiyotik_200ml:{
        id: 89,
        name: 'Pinar Kefir Probiyotik 200ml',
        brand: 'Pinar',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/11559500/11559500-facfb1',
        price: 1.7,
        discount: 0,
        unit: 'Piece',
        path: 'beverage/Pinar_Kefir_Probiyotik_200ml'
      },
      Eker_Ayran_293ml:{
        id: 90,
        name: 'Eker Ayran 293ml',
        brand: 'Eker',
        title: 'Beverage',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/11552678/11552678-a46684',
        price: 0.5,
        discount: 0,
        unit: 'Piece',
        path: 'beverage/Eker_Ayran_293ml'
      },
    }
  },
  detergent_cleaning: {
    id: 6,
    title: 'Detergent and Cleaning',
    routeName: 'detergent_cleaning',
    items: {
      Calgon_Ekolojik_Kireç_Önleyici_750_Ml:{
        id: 91,
        name: 'Calgon Ekolojik Kireç Önleyici 750 Ml',
        brand: 'Calgon',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/30348325/30348325-88ea41',
        price: 3,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Calgon_Ekolojik_Kireç_Önleyici_750_Ml'
      },
      Calgon_Ekstra_Hijyen_Toz_500G:{
        id: 92,
        name: 'Calgon Ekstra Hijyen Toz 500 G',
        brand: 'Calgon',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/30348324/30348324-84ffa4',
        price: 2,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Calgon_Ekstra_Hijyen_Toz_500G'
      },
      Marc_Çamaşır_Makinesi_Temizleyici_Floral:{
        id: 93,
        name: 'Marc Çamaşır Makinesi Temizleyici Floral',
        brand: 'Marc',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/30628720/30628720-2754b7',
        price: 2,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Marc_Çamaşır_Makinesi_Temizleyici_Floral'
      },
      Finish_Çift_Etkili_Makine_Temizleyici_Limon_250_Ml:{
        id: 94,
        name: 'Finish Çift Etkili Makine Temizleyici Limon 250 Ml',
        brand: 'Finish',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/30403281/30403281-83a65f',
        price: 2.5,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Finish_Çift_Etkili_Makine_Temizleyici_Limon_250_Ml'
      },
      Finish_Makine_Temizleyici_Tablet:{
        id: 95,
        name: 'Finish Makine Temizleyici Tablet',
        brand: 'Finish',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/30431847/30431847-f82a50',
        price: 4,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Finish_Makine_Temizleyici_Tablet'
      },
      Pril_Makine_Temizleyici_Kapsül_3X19G:{
        id: 96,
        name: 'Pril Makine Temizleyici Kapsül 3X19 G',
        brand: 'Pril',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/30431848/30431848-b6debf',
        price: 2.1,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Pril_Makine_Temizleyici_Kapsül_3X19G'
      },
      Bulaşık_Makinesi_Temizleyici_2X20G:{
        id: 97,
        name: 'Bulaşık Makinesi Temizleyici 2X20 G',
        brand: 'Calgon',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/30403301/30403301-8209ef',
        price: 2.5,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Bulaşık_Makinesi_Temizleyici_2X20G'
      },
      Alo_Platinum_Çamaşır_Deterjanı:{
        id: 98,
        name: 'Alo Platinum Çamaşır Deterjanı Fairy Etkili Renkli 1.69 L',
        brand: 'Alo',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/30539727/30539727-75eeb3',
        price: 2.5,
        discount: 0.1,
        unit: 'Piece',
        path: 'detergent_cleaning/Alo_Platinum_Çamaşır_Deterjanı'
      },
      Vanish_Sıvı_Gold_Beyaz_1000Ml:{
        id: 99,
        name: 'Vanish Sıvı Gold Beyaz 1000 Ml',
        brand: 'Vanish',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/30569718/30569718-201e88',
        price: 2.5,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Vanish_Sıvı_Gold_Beyaz_1000Ml'
      },
      Detan_60Gece_Elektrolikit_Cihaz:{
        id: 100,
        name: 'Detan 60 Gece Elektrolikit Cihaz + Yedek',
        brand: 'Detan',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31556040/31556040-d1a423',
        price: 1.5,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Detan_60Gece_Elektrolikit_Cihaz'
      },
      Detan_Maxi_Böcek_İlacı:{
        id: 101,
        name: 'Detan Maxi Böcek İlacı 250 Ml',
        brand: 'Detan',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31552045/31552045-7d7286',
        price: 1.8,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Detan_Maxi_Böcek_İlacı'
      },
      Bion_Böceklere_Karşı_Etkili_Aerosol:{
        id: 102,
        name: 'Bion Böceklere Karşı Etkili Aerosol 405 Ml',
        brand: 'Bion',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31550010/31550010-0677fe',
        price: 2.5,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Bion_Böceklere_Karşı_Etkili_Aerosol'
      },
      Raid_Sinek_Öldürücü_Sprey:{
        id: 103,
        name: 'Raid Sinek Öldürücü Sprey 300Ml',
        brand: 'Raid',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31550120/31550120-b9d208',
        price: 2.5,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/cRaid_Sinek_Öldürücü_Sprey'
      },
      Raid_Elektro_Likit:{
        id: 104,
        name: 'Raid Elektro Likit',
        brand: 'Raid',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31556000/31556000-dad2fd',
        price: 1.4,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Raid_Elektro_Likit'
      },
      Solo_Tüm_Yüzeyler_Islak_Temizlik_Bezi:{
        id: 105,
        name: 'Solo Tüm Yüzeyler Islak Temizlik Bezi 40x',
        brand: 'Solo',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31163669/31163669-f3d1b2',
        price: 0.5,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Solo_Tüm_Yüzeyler_Islak_Temizlik_Bezi'
      },
      Parex_Mikrofiber_Yer_Bezi:{
        id: 106,
        name: 'Parex Mikrofiber Yer Bezi',
        brand: 'Parex',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31163651/parex-mikrofiber-yer-bezi-05432a',
        price: 1,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Parex_Mikrofiber_Yer_Bezi'
      },
      Yer_Bezi_50x60cm:{
        id: 107,
        name: 'Yer Bezi 50x60cm',
        brand: 'Kazim',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31160019/31160019-c9727c',
        price: 0.9,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Yer_Bezi_50x60cm'
      },
      Scotch_Brite_Islak_Banyo_Bezi_50x:{
        id: 108,
        name: 'Scotch Brite Islak Banyo Bezi 50x',
        brand: 'Scotch Brite',
        title: 'Detergent and Cleaning',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31030014/31030014-5d4534',
        price: 0.5,
        discount: 0,
        unit: 'Piece',
        path: 'detergent_cleaning/Scotch_Brite_Islak_Banyo_Bezi_50x'
      },
    }
  },
  paper_cosmetics: {
    id: 7,
    title: 'Paper and Cosmetics',
    routeName: 'paper_cosmetics',
    items: {
      Papia_Kutu_Mendil_100x:{
        id: 109,
        name: 'Papia Kutu Mendil 100x',
        brand: 'Papia',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31030057/31030057-6cf202',
        price: 0.8,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Papia_Kutu_Mendil_100x'
      },
      Duni_Masa_Örtüsü_120X180_Cm:{
        id: 110,
        name: 'Duni Masa Örtüsü 120X180 Cm',
        brand: 'Duni',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31049130/duni-masa-ortusu-120-180cm-fe47da',
        price: 2,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Duni_Masa_Örtüsü_120X180_Cm'
      },
      Sofia_Renk_Renk_Desenli_Peçete_20x:{
        id: 111,
        name: 'Sofia Renk Renk Desenli Peçete 20x',
        brand: 'Sofia',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31049138/31049138-f332de',
        price: 1.1,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Sofia_Renk_Renk_Desenli_Peçete_20x'
      },
      Selpak_Trend_Peçete_20x:{
        id: 112,
        name: 'Selpak Trend Peçete 20x',
        brand: 'Selpak',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31049135/31049135-f197d8',
        price: 0.3,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Selpak_Trend_Peçete_20x'
      },
      Duni_40X40_Elegance_Kumaş_Dokulu_Peçete_10x:{
        id: 113,
        name: 'Duni 40X40 Elegance Kumaş Dokulu Peçete 10x',
        brand: 'Duni',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31040952/duni-elegance-pecete-40x40-10-lu-fc9428',
        price: 0.7,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Duni_40X40_Elegance_Kumaş_Dokulu_Peçete_10x'
      },
      Papia_Decor_Peçete_20x:{
        id: 114,
        name: 'Papia Decor Peçete 20x',
        brand: 'Scotch Brite',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31041704/31041704-eb13ef',
        price: 1.2,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Papia_Decor_Peçete_20x'
      },
      Selpak_Deluxe_Peçete_20x:{
        id: 115,
        name: 'Selpak Deluxe Peçete 20x',
        brand: 'Selpak',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31049162/31049162-a35e70',
        price: 1.4,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Selpak_Deluxe_Peçete_20x'
      },
      Selpak_Tuvalet_Kagıdı_32x:{
        id: 116,
        name: 'Selpak Tuvalet Kağıdı 32x',
        brand: 'Selpak',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31012008/31012008-1bbe47',
        price: 2.5,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Selpak_Tuvalet_Kagıdı_32x'
      },
      Papia_Tuvalet_Kagıdı_32x:{
        id: 117,
        name: 'Papia Tuvalet Kağıdı 32x',
        brand: 'Papia',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31019960/31019960-757421',
        price: 3.1,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Papia_Tuvalet_Kagıdı_32x'
      },
      Mare_Ultra_Tuvalet_Kağıdı_16x:{
        id: 118,
        name: 'Mare Ultra Tuvalet Kağıdı 16x',
        brand: 'Mare',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31010880/31010880-65eadc',
        price: 1.8,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Mare_Ultra_Tuvalet_Kağıdı_16x'
      },
      Neutrogena_Hızlı_Emilen_Bakım_Kremi:{
        id: 119,
        name: 'Neutrogena Hızlı Emilen Bakım Kremi 200 Ml',
        brand: 'Scotch Brite',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/35409242/35409242-9c3b2b',
        price: 1.9,
        discount: 0.2,
        unit: 'Piece',
        path: 'paper_cosmetics/Neutrogena_Hızlı_Emilen_Bakım_Kremi'
      },
      Familia_Plus_Bambu_Tuvalet_Kağıdı_16x:{
        id: 120,
        name: 'Familia Plus Bambu Tuvalet Kağıdı 16x',
        brand: 'Scotch Brite',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31010026/31010026-da5bf3',
        price: 2.1,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Familia_Plus_Bambu_Tuvalet_Kağıdı_16x'
      },
      Ecco_Yeşil_Dünya_Tuvalet_Kağıdı_12x:{
        id: 121,
        name: 'Ecco Yeşil Dünya Tuvalet Kağıdı 12x',
        brand: 'Scotch Brite',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31011983/31011983-943887',
        price: 4.1,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Ecco_Yeşil_Dünya_Tuvalet_Kağıdı_12x'
      },
      Uni_Baby_Classic_Islak_Havlu_3X56:{
        id: 122,
        name: 'Uni Baby Classic Islak Havlu 3X56',
        brand: 'Scotch Brite',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31030044/31030044-f0a0f1',
        price: 3.1,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Uni_Baby_Classic_Islak_Havlu_3X56'
      },      
      Uni_Baby_Simple_Clean_Islak_Havlu_3X52:{
        id: 123,
        name: 'Uni Baby Simple Clean Islak Havlu 3X52',
        brand: 'Scotch Brite',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31030047/31030047-1474c1',
        price: 1.5,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Uni_Baby_Simple_Clean_Islak_Havlu_3X52'
      },
      Pastel_Oje_19:{
        id: 124,
        name: 'Pastel Oje 19',
        brand: 'Scotch Brite',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/35990115/35990115-adf566',
        price: 0.5,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Pastel_Oje_19'
      },
      Lionesse_12445_Sivri_Uçlu_Et_Pensi:{
        id: 125,
        name: 'Lionesse 12445 Sivri Uçlu Et Pensi',
        brand: 'Scotch Brite',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/35479137/35479137-e9c02e-1650x1650.png',
        price: 1.4,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Lionesse_12445_Sivri_Uçlu_Et_Pensi'
      },
      Palmolive_Duş_Jeli_500_Ml:{
        id: 126,
        name: 'Palmolive Duş Jeli 500 Ml',
        brand: 'Scotch Brite',
        title: 'Paper and Cosmetics',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/34379305/34379305-18cc37',
        price: 1.3,
        discount: 0,
        unit: 'Piece',
        path: 'paper_cosmetics/Palmolive_Duş_Jeli_500_Ml'
      },
    }
  },
  baby_toys: {
    id: 8,
    title: 'Baby and Toys',
    routeName: 'baby_toys',
    items: {
      Pritt_Oyun_Hamuru_4X100G:{
        id: 127,
        name: 'Pritt Oyun Hamuru 4X100 G',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/36034543/pritt-oyun-hamuru-4x100-gr-4-renk-840ac0',
        price: 2,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Pritt_Oyun_Hamuru_4X100G'
      },
      Fisher_Price_Şekilleri_Öğreniyorum_Oyun_Seti:{
        id: 128,
        name: 'Fisher Price Şekilleri Öğreniyorum Oyun Seti',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/36060859/36060859-a4378c',
        price: 2.8,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Fisher_Price_Şekilleri_Öğreniyorum_Oyun_Seti'
      },
      Playdoh_4x_Hamur_4X112G:{
        id: 129,
        name: 'Playdoh 4x Hamur 4X112 G',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/36036305/36036305-59a68d',
        price: 1.8,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Playdoh_4x_Hamur_4X112G'
      },
      Yılbaşı_Oyun_Hamur_Seti:{
        id: 130,
        name: 'Yılbaşı Oyun Hamur Seti',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/36060852/36060852-9c6cec',
        price: 2.9,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Yılbaşı_Oyun_Hamur_Seti'
      },
      Karlar_Ülkesi_Cars_Kinetik_Kum_2X200G:{
        id: 131,
        name: 'Karlar Ülkesi/Cars Kinetik Kum 2X200 G',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/36037712/36037712-45726f',
        price: 2.6,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Karlar_Ülkesi_Cars_Kinetik_Kum_2X200G'
      },
      Hotwheels_Tekli_Arabalar:{
        id: 132,
        name: 'Hotwheels Tekli Arabalar',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/36252238/atm-tekli-arabalar-b3b535',
        price: 1,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/ Hotwheels_Tekli_Arabalar'
      },
      Matchbox_Tekli_Arabalar:{
        id: 133,
        name: 'Matchbox Tekli Arabalar',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/36036065/36036065-5b2093',
        price: 1.2,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Matchbox_Tekli_Arabalar'
      },
      Prima_Pure_Bebek_Bezi_5_Beden_17x:{
        id: 134,
        name: 'Prima Pure Bebek Bezi 5 Beden 17x',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31100224/31100224-b3a891',
        price: 6.4,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Prima_Pure_Bebek_Bezi_5_Beden_17x'
      },
      Prima_5_Beden_Premium_Care_Junior_Ekonomik_42_Adet:{
        id: 135,
        name: 'Prima 5 Beden Premium Care Junior Ekonomik 42 Adet',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31108181/31108181-136e3e',
        price: 8,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Prima_5_Beden_Premium_Care_Junior_Ekonomik_42_Adet'
      },
      Koroplast_Pudra_Kokulu_Bebek_Bezi_Torbası_50x:{
        id: 136,
        name: 'Koroplast Pudra Kokulu Bebek Bezi Torbası 50x',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/31108203/31108203-1d624d',
        price: 1.4,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Koroplast_Pudra_Kokulu_Bebek_Bezi_Torbası_50x'
      },
      Nivea_Bebek_Pişik_Kremi_100Ml:{
        id: 137,
        name: 'Nivea Bebek Pişik Kremi 100 Ml',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/35320401/35320401-c35b72',
        price: 4,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Nivea_Bebek_Pişik_Kremi_100Ml'
      },
      Sebamed_Bebek_Pişik_Önleyici_Krem_100Ml:{
        id: 138,
        name: 'Sebamed Bebek Pişik Önleyici Krem 100 Ml',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/35325125/sebamed-baby-pisik-onleyici-krem-100-ml-fc16a1',
        price: 4.6,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Sebamed_Bebek_Pişik_Önleyici_Krem_100Ml'
      },
      Wee_Baby_Renkli_Sulu_Diş_Halkası:{
        id: 139,
        name: 'Wee Baby Renkli Sulu Diş Halkası',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/46024633/wee-bbay-renkli-sulu-dis-halkasi-201-55fe4f',
        price: 1.8,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Wee_Baby_Renkli_Sulu_Diş_Halkas'
      },
      Sma_Komfort_Bebek_Devam_Sütü_1_400G:{
        id: 140,
        name: 'Sma Comfort Bebek Devam Sütü 1 400 G',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05040550/05040550-8c2f70',
        price: 9,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Sma_Komfort_Bebek_Devam_Sütü_1_400G'
      },
      Aptamil_Conformil_1_Bebek_Sütü_300G:{
        id: 141,
        name: 'Aptamil Conformil 1 Bebek Sütü 300 G',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05046816/aptamil-conformil-1-bebek-sutu-300-gr-c78314',
        price: 6,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Aptamil_Conformil_1_Bebek_Sütü_300G'
      },
      Aptamil_1_Bebek_Sütü_350_G_0_6_Ay_Akıllı_Kutu:{
        id: 142,
        name: 'Aptamil 1 Bebek Sütü 350 G 0-6 Ay Akıllı Kutu',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05040563/05040563-021ace',
        price: 9,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Aptamil_1_Bebek_Sütü_350_G_0_6_Ay_Akıllı_Kutu'
      },
      Elite_Naturel_Karşık_Meyveli_Soğuk_Anne_Çayı_200Ml:{
        id: 143,
        name: 'Elite Naturel Karşık Meyveli Soğuk Anne Çayı 200 Ml',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05040548/05040548-b5c1ca',
        price: 0.6,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Elite_Naturel_Karşık_Meyveli_Soğuk_Anne_Çayı_200Ml'
      },
      Hero_Baby_Şeftali_Muz_Püreli_Kavanoz_Mama_125G:{
        id: 144,
        name: 'Hero Baby Şeftali Muz Püreli Kavanoz Mama 125 G',
        brand: 'Scotch Brite',
        title: 'Baby and Toys',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05046694/05046694-c52993',
        price: 0.7,
        discount: 0,
        unit: 'Piece',
        path: 'baby_toys/Hero_Baby_Şeftali_Muz_Püreli_Kavanoz_Mama_125G'
      },
    }
  },
  home_pet: {
    id: 9,
    title: 'Home and Pet',
    routeName: 'home_pet',
    items: {
      Snorkel_14:{
        id: 145,
        name: 'Şnorkel +14',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/36807297/snorkel-14-df0f92',
        price: 2.3,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Snorkel_14'
      },
      Nk_Yoga_Matı_155X60CmX5Mm:{
        id: 146,
        name: 'Nk Yoga Matı 155 X 60 Cm X 5Mm',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/38017717/38017717-41ae78',
        price: 10,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Nk_Yoga_Matı_155X60CmX5Mm'
      },
      Bestway_Spiderman_Can_Yeleği_51x46_Cm:{
        id: 147,
        name: 'Bestway Spiderman Can Yeleği 51x46 Cm',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/36807283/spiderman-can-yelegi-20-x-18-51-cm-x-46-cm-swim-v-48d749',
        price: 4.6,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Bestway_Spiderman_Can_Yeleği_51x46_Cm'
      },
      Axentia_Sugar_Yazılı_Cam_Kavanoz_1700Ml:{
        id: 148,
        name: 'Axentia Sugar Yazılı Cam Kavanoz 1700 Ml',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/33037703/33037703-c7bdbc',
        price: 3,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Axentia_Sugar_Yazılı_Cam_Kavanoz_1700Ml'
      },
      Paşabahçe_Woody_Bambu_Kapaklı_Kavanoz_575_Cc:{
        id: 149,
        name: 'Paşabahçe Woody Bambu Kapaklı Kavanoz 575 Cc',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/33010696/33010696-3cc05f',
        price: 1.6,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Paşabahçe_Woody_Bambu_Kapaklı_Kavanoz_575_Cc'
      },
      Paşabahçe_Woody_Bambu_Kapaklı_Kavanoz_860Cc:{
        id: 150,
        name: 'Paşabahçe Woody Bambu Kapaklı Kavanoz 860Cc',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/33010697/33010697-2577d7',
        price: 1.7,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Paşabahçe_Woody_Bambu_Kapaklı_Kavanoz_860Cc'
      },
      Koroplast_Büyük_Boy_Buzdolabı_Poşeti_20x:{
        id: 151,
        name: 'Koroplast Büyük Boy Buzdolabı Poşeti 20x',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/32095005/korozo-buyuk-boy-buzdolabi-poseti-0eabe9',
        price: 0.6,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Koroplast_Büyük_Boy_Buzdolabı_Poşeti_20x'
      },
      Koroplast_Buzdolabı_Poşeti_Orta_Boy:{
        id: 152,
        name: 'Koroplast Buzdolabı Poşeti Orta Boy 4 Al 3 Öde 120x',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/32090020/koroplast-buzdolabi-poseti-orta-boy-4-al-3-ode-paketinde-0fb9b1',
        price: 1.3,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Koroplast_Buzdolabı_Poşeti_Orta_Boy'
      },
      Cook_Orta_Boy_Buzdolabı_Poşeti:{
        id: 153,
        name: 'Cook Orta Boy Buzdolabı Poşeti',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/32095097/32095097-bb7946',
        price: 0.5,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Cook_Orta_Boy_Buzdolabı_Poşeti'
      },
      Filpa_Körüklü_Pipet_40x:{
        id: 154,
        name: 'Filpa Körüklü Pipet 40x',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/32300425/filpa-koruklu-pipet-40-li-e0b1f9',
        price: 0.3,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Filpa_Körüklü_Pipet_40x'
      },
      Leva_Koli_Bandı_100M:{
        id: 155,
        name: 'Leva Koli Bandı 100 M',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/44257028/44257028-8300de',
        price: 0.7,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Leva_Koli_Bandı_100M'
      },
      Duck_Şeffaf_Koli_Bandı_45Mmx40m:{
        id: 156,
        name: 'Duck Şeffaf Koli Bandı 45Mmx40m',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/44108152/44108152-22e376',
        price: 0.65,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Duck_Şeffaf_Koli_Bandı_45Mmx40m'
      },
      Nilson_3lü_1_Metre_Topraklı_Grup_Priz:{
        id: 157,
        name: 'Nilson 3lü 1 Metre Topraklı Grup Priz',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39149214/39149214-bfbb0f',
        price: 2.5,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Nilson_3lü_1_Metre_Topraklı_Grup_Priz'
      },
      Leva_House_136_Parça_Vida_Montaj_Seti:{
        id: 158,
        name: 'Leva House 136 Parça Vida/Montaj Seti',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/44050707/44050707-094d81',
        price: 1.9,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Leva_House_136_Parça_Vida_Montaj_Seti'
      },
      Sıcak_Su_Torbası_2L:{
        id: 159,
        name: 'Sıcak Su Torbası 2 L',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/44251522/sicak-su-torbasi-2-l-d57f2c',
        price: 2,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/ Sıcak_Su_Torbası_2L'
      },
      Kazaklı_Sıcak_Su_Torbası_2L:{
        id: 160,
        name: 'Kazaklı Sıcak Su Torbası 2 L',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/44251535/44251535-6c7f6a',
        price: 2.5,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Kazaklı_Sıcak_Su_Torbası_2L'
      },
      Homebasix_Cok_Amaclı_Kaydırmaz_45X100_Cm:{
        id: 161,
        name: 'Homebasix Çok Amaçlı Kaydırmaz 45X100 Cm',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/44251477/44251477-7831d8',
        price: 1.3,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Homebasix_Cok_Amaclı_Kaydırmaz_45X100_Cm'
      },
      Leva_Seffaf_Raf_Örtüsü_45X90_Cm:{
        id: 162,
        name: 'Leva Şeffaf Raf Örtüsü 45X90 Cm',
        brand: 'Scotch Brite',
        title: 'Home and Pet',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/44253333/44253333-4c1d09',
        price: 1.7,
        discount: 0,
        unit: 'Piece',
        path: 'home_pet/Leva_Seffaf_Raf_Örtüsü_45X90_Cm'
      },
    }
  },
  electronic: {
    id: 10,
    title: 'Electronic',
    routeName: 'electronic',
    items: {
      Bood_Bluetooth_Kulaklık_Ls_15:{
        id: 163,
        name: 'Bood Bluetooth Kulaklık Ls-15',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39280726/39280726-0bd443',
        price: 21,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/Bood_Bluetooth_Kulaklık_Ls_15'
      },
      Bood_Kablosuz_Kulaklık_M62:{
        id: 164,
        name: 'Bood Kablosuz Kulaklık M-62',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39280725/39280725-3e4055',
        price: 16,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/Bood_Kablosuz_Kulaklık_M62'
      },
      Bood_Kablosuz_Renkli_Kulaklık_P4:{
        id: 165,
        name: 'Bood Kablosuz Renkli Kulaklık P-4',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39280724/39280724-2fe0da',
        price: 12,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/Bood_Kablosuz_Renkli_Kulaklık_P4'
      },
      Think_New_Universal_Mikrofonlu_Kulaklik:{
        id: 166,
        name: 'Think New Universal Mikrofonlu Kulaklık',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39183033/39183033-9daf65',
        price: 5,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/Think_New_Universal_Mikrofonlu_Kulaklik'
      },
      Think_Type_C_Sarj_Data_Kablo_1_Metre:{
        id: 167,
        name: 'Think Type-C Şarj & Data Kablo 1 Metre',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39182415/39182415-8439bf',
        price: 2,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/Think_Type_C_Sarj_Data_Kablo_1_Metre'
      },
      Aprilla_Exclusive_Ahd_2127_Sac_Kurutma_Makinesi:{
        id: 168,
        name: 'Aprilla Exclusive Ahd-2127 Saç Kurutma Makinesi',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39066188/39066188-f228e9',
        price: 9,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/Aprilla_Exclusive_Ahd_2127_Sac_Kurutma_Makinesi'
      },
      Kiwi_Ksm_2405w_Waffle_Makinesi:{
        id: 169,
        name: 'Kiwi Ksm-2405w Waffle Makinesi',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39026022/39026022-bdd91f',
        price: 12,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/Kiwi_Ksm_2405w_Waffle_Makinesi'
      },
      General_Home_Q9001_4K_Uhd_Saat_Hediyeli_Aksiyon_Kamera:{
        id: 170,
        name: 'General Home Q9001 4K Uhd Saat Hediyeli Aksiyon Kamera',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39398041/39398041-3fe81c',
        price: 54,
        discount: 0.2,
        unit: 'Piece',
        path: 'electronic/General_Home_Q9001_4K_Uhd_Saat_Hediyeli_Aksiyon_Kamera'
      },
      Rowell_2000W_Elektrikli_Fan_Isıtıcı_Lq_501:{
        id: 171,
        name: 'Rowell 2000W Elektrikli Fan Isıtıcı Lq-501',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39151230/39151230-6af964',
        price: 7,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/Rowell_2000W_Elektrikli_Fan_Isıtıcı_Lq_501'
      },
      Kumtel_Lx_2832_1500W_Delux_Siyah_Isıtıcı:{
        id: 172,
        name: 'Kumtel Lx-2832 1500W Delux Siyah Isıtıcı',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39155992/39155992-5017b8',
        price: 10,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/Kumtel_Lx_2832_1500W_Delux_Siyah_Isıtıcı'
      },
      My_Style_Dekoratif_Led_Isık_Yıldız_Kalp:{
        id: 173,
        name: 'My Style Dekoratif Led Işık Yıldız/Kalp',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119935/39119935-c7c133',
        price: 8,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/My_Style_Dekoratif_Led_Isık_Yıldız_Kalp'
      },
      Urban_Mood_Dekoratif_Işık_Zinciri_8_Mod:{
        id: 174,
        name: 'Urban Mood Dekoratif Işık Zinciri 8 Mod',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119939/39119939-e908d9',
        price: 5,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/Urban_Mood_Dekoratif_Işık_Zinciri_8_Mod'
      },
      Urban_Mood_16_Dekoratif_Led_Top_Isık_Zinciri:{
        id: 175,
        name: 'Urban Mood 16 Dekoratif Led Top Işık Zinciri',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119940/39119940-0ceb66',
        price: 8,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/Urban_Mood_16_Dekoratif_Led_Top_Isık_Zinciri'
      },
      Mystyle_12li_Led_Isıklı_Foto_Mandal:{
        id: 176,
        name: 'Mystyle 12li Led Işıklı Foto Mandal',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119924/39119924-e84216',
        price: 4,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/Mystyle_12li_Led_Isıklı_Foto_Mandal'
      },
      Urban_Mood_Retro_Dekoratif_Led_Işık_Top_4lü:{
        id: 177,
        name: 'Urban Mood Retro Dekoratif Led Işık Top 4lü',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119938/39119938-b03d61',
        price: 8,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/Urban_Mood_Retro_Dekoratif_Led_Işık_Top_4lü'
      },
      General_Home_El_Feneri_Df25:{
        id: 178,
        name: 'General Home El Feneri Df-25',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39109970/39109970-131a6c',
        price: 2,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/General_Home_El_Feneri_Df25'
      },
      Nilson_3lü_Golyat_Topraklı_Fiş_Priz_Siyah:{
        id: 179,
        name: 'Nilson 3lü Golyat - Topraklı Fiş Priz (Siyah)',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/46064715/46064715-9f5ef1',
        price: 1.3,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/Nilson_3lü_Golyat_Topraklı_Fiş_Priz_Siyah'
      },
      glow_worm_3lü_anahtarlı_5M:{
        id: 180,
        name: 'Glow-worm 3lü Anahtarlı  5 M',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39100264/glow-worm-3-lu-anahtarli-5-mt-315f11',
        price: 5,
        discount: 0,
        unit: 'Piece',
        path: 'electronic/glow_worm_3lü_anahtarlı_5M'
      },
  }
  },
  discounts: {
    id: 11,
    title: 'Discounts',
    routeName: 'discounts',
    items: {
      Bood_Bluetooth_Kulaklık_Ls_15:{
        id: 181,
        name: 'Bood Bluetooth Kulaklık Ls-15',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39280726/39280726-0bd443',
        price: 21,
        discount: 0.1,
        unit: 'Piece',
        path: 'discounts/Bood_Bluetooth_Kulaklık_Ls_15'
      },
      Bood_Kablosuz_Kulaklık_M62:{
        id: 182,
        name: 'Bood Kablosuz Kulaklık M-62',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39280725/39280725-3e4055',
        price: 16,
        discount: 0.1,
        unit: 'Piece',
        path: 'discounts/Bood_Kablosuz_Kulaklık_M62'
      },
      Bood_Kablosuz_Renkli_Kulaklık_P4:{
        id: 183,
        name: 'Bood Kablosuz Renkli Kulaklık P-4',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39280724/39280724-2fe0da',
        price: 12,
        discount: 0.2,
        unit: 'Piece',
        path: 'discounts/Bood_Kablosuz_Renkli_Kulaklık_P4'
      },
      Think_New_Universal_Mikrofonlu_Kulaklik:{
        id: 184,
        name: 'Think New Universal Mikrofonlu Kulaklık',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39183033/39183033-9daf65',
        price: 5,
        discount: 0.2,
        unit: 'Piece',
        path: 'discounts/Think_New_Universal_Mikrofonlu_Kulaklik'
      },
      Think_Type_C_Sarj_Data_Kablo_1_Metre:{
        id: 185,
        name: 'Think Type-C Şarj & Data Kablo 1 Metre',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39182415/39182415-8439bf',
        price: 2,
        discount: 0.2,
        unit: 'Piece',
        path: 'discounts/Think_Type_C_Sarj_Data_Kablo_1_Metre'
      },
      Aprilla_Exclusive_Ahd_2127_Sac_Kurutma_Makinesi:{
        id: 186,
        name: 'Aprilla Exclusive Ahd-2127 Saç Kurutma Makinesi',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39066188/39066188-f228e9',
        price: 9,
        discount: 0.2,
        unit: 'Piece',
        path: 'discounts/Aprilla_Exclusive_Ahd_2127_Sac_Kurutma_Makinesi'
      },
      Kiwi_Ksm_2405w_Waffle_Makinesi:{
        id: 187,
        name: 'Kiwi Ksm-2405w Waffle Makinesi',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39026022/39026022-bdd91f',
        price: 12,
        discount: 0.2,
        unit: 'Piece',
        path: 'discounts/Kiwi_Ksm_2405w_Waffle_Makinesi'
      },
      General_Home_Q9001_4K_Uhd_Saat_Hediyeli_Aksiyon_Kamera:{
        id: 170,
        name: 'General Home Q9001 4K Uhd Saat Hediyeli Aksiyon Kamera',
        brand: 'Scotch Brite',
        title: 'Electronic',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39398041/39398041-3fe81c',
        price: 54,
        discount: 0.2,
        unit: 'Piece',
        path: 'electronic/General_Home_Q9001_4K_Uhd_Saat_Hediyeli_Aksiyon_Kamera'
      },
      Rowell_2000W_Elektrikli_Fan_Isıtıcı_Lq_501:{
        id: 189,
        name: 'Rowell 2000W Elektrikli Fan Isıtıcı Lq-501',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39151230/39151230-6af964',
        price: 7,
        discount: 0.1,
        unit: 'Piece',
        path: 'discounts/Rowell_2000W_Elektrikli_Fan_Isıtıcı_Lq_501'
      },
      Kumtel_Lx_2832_1500W_Delux_Siyah_Isıtıcı:{
        id: 190,
        name: 'Kumtel Lx-2832 1500W Delux Siyah Isıtıcı',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39155992/39155992-5017b8',
        price: 10,
        discount: 0.2,
        unit: 'Piece',
        path: 'discounts/Kumtel_Lx_2832_1500W_Delux_Siyah_Isıtıcı'
      },
      My_Style_Dekoratif_Led_Isık_Yıldız_Kalp:{
        id: 191,
        name: 'My Style Dekoratif Led Işık Yıldız/Kalp',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119935/39119935-c7c133',
        price: 8,
        discount: 0.1,
        unit: 'Piece',
        path: 'discounts/My_Style_Dekoratif_Led_Isık_Yıldız_Kalp'
      },
      Urban_Mood_Dekoratif_Işık_Zinciri_8_Mod:{
        id: 192,
        name: 'Urban Mood Dekoratif Işık Zinciri 8 Mod',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119939/39119939-e908d9',
        price: 5,
        discount: 0.1,
        unit: 'Piece',
        path: 'discounts/Urban_Mood_Dekoratif_Işık_Zinciri_8_Mod'
      },
      Urban_Mood_16_Dekoratif_Led_Top_Isık_Zinciri:{
        id: 193,
        name: 'Urban Mood 16 Dekoratif Led Top Işık Zinciri',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119940/39119940-0ceb66',
        price: 8,
        discount: 0.1,
        unit: 'Piece',
        path: 'discounts/Urban_Mood_16_Dekoratif_Led_Top_Isık_Zinciri'
      },
      Mystyle_12li_Led_Isıklı_Foto_Mandal:{
        id: 194,
        name: 'Mystyle 12li Led Işıklı Foto Mandal',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119924/39119924-e84216',
        price: 4,
        discount: 0.2,
        unit: 'Piece',
        path: 'discounts/Mystyle_12li_Led_Isıklı_Foto_Mandal'
      },
      Urban_Mood_Retro_Dekoratif_Led_Işık_Top_4lü:{
        id: 195,
        name: 'Urban Mood Retro Dekoratif Led Işık Top 4lü',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119938/39119938-b03d61',
        price: 8,
        discount: 0.1,
        unit: 'Piece',
        path: 'discounts/Urban_Mood_Retro_Dekoratif_Led_Işık_Top_4lü'
      },
      General_Home_El_Feneri_Df25:{
        id: 196,
        name: 'General Home El Feneri Df-25',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39109970/39109970-131a6c',
        price: 2,
        discount: 0.1,
        unit: 'Piece',
        path: 'discounts/General_Home_El_Feneri_Df25'
      },
      Nilson_3lü_Golyat_Topraklı_Fiş_Priz_Siyah:{
        id: 197,
        name: 'Nilson 3lü Golyat - Topraklı Fiş Priz (Siyah)',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/46064715/46064715-9f5ef1',
        price: 1.3,
        discount: 0.1,
        unit: 'Piece',
        path: 'discounts/Nilson_3lü_Golyat_Topraklı_Fiş_Priz_Siyah'
      },
      glow_worm_3lü_anahtarlı_5M:{
        id: 198,
        name: 'Glow-worm 3lü Anahtarlı  5 M',
        brand: 'Scotch Brite',
        title: 'Discounts',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39100264/glow-worm-3-lu-anahtarli-5-mt-315f11',
        price: 5,
        discount: 0.1,
        unit: 'Piece',
        path: 'discounts/glow_worm_3lü_anahtarlı_5M'
      },
  }
  },
  hakanskop: {
    id: 12,
    title: 'Hakanskop',
    routeName: 'hakanskop',
    items: {
      Bood_Bluetooth_Kulaklık_Ls_15:{
        id: 199,
        name: 'Bood Bluetooth Kulaklık Ls-15',
        brand: 'Scotch Brite',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39280726/39280726-0bd443',
        price: 21,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Bood_Bluetooth_Kulaklık_Ls_15'
      },
      Bood_Kablosuz_Kulaklık_M62:{
        id: 200,
        name: 'Bood Kablosuz Kulaklık M-62',
        brand: 'Scotch Brite',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39280725/39280725-3e4055',
        price: 16,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Bood_Kablosuz_Kulaklık_M62'
      },
      Bood_Kablosuz_Renkli_Kulaklık_P4:{
        id: 201,
        name: 'Bood Kablosuz Renkli Kulaklık P-4',
        brand: 'Scotch Brite',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39280724/39280724-2fe0da',
        price: 12,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Bood_Kablosuz_Renkli_Kulaklık_P4'
      },
      Think_New_Universal_Mikrofonlu_Kulaklik:{
        id: 202,
        name: 'Think New Universal Mikrofonlu Kulaklık',
        brand: 'Scotch Brite',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39183033/39183033-9daf65',
        price: 5,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Think_New_Universal_Mikrofonlu_Kulaklik'
      },
      Think_Type_C_Sarj_Data_Kablo_1_Metre:{
        id: 203,
        name: 'Think Type-C Şarj & Data Kablo 1 Metre',
        brand: 'Think',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39182415/39182415-8439bf',
        price: 2,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Think_Type_C_Sarj_Data_Kablo_1_Metre'
      },
      Aprilla_Exclusive_Ahd_2127_Sac_Kurutma_Makinesi:{
        id: 204,
        name: 'Aprilla Exclusive Ahd-2127 Saç Kurutma Makinesi',
        brand: 'Aprilla',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39066188/39066188-f228e9',
        price: 9,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Aprilla_Exclusive_Ahd_2127_Sac_Kurutma_Makinesi'
      },
      Kiwi_Ksm_2405w_Waffle_Makinesi:{
        id: 205,
        name: 'Kiwi Ksm-2405w Waffle Makinesi',
        brand: 'Kiwi',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39026022/39026022-bdd91f',
        price: 12,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Kiwi_Ksm_2405w_Waffle_Makinesi'
      },
      Arzum_Ar1123_Ar1123_B_Ecomix_Mikser:{
        id: 206,
        name: 'Arzum Ar1123 Ar1123-B Ecomix Mikser',
        brand: 'Arzum',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39046564/39046564-dbd42d',
        price: 25,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Arzum_Ar1123_Ar1123_B_Ecomix_Mikser'
      },
      Rowell_2000W_Elektrikli_Fan_Isıtıcı_Lq_501:{
        id: 207,
        name: 'Rowell 2000W Elektrikli Fan Isıtıcı Lq-501',
        brand: 'Rowell',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39151230/39151230-6af964',
        price: 7,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Rowell_2000W_Elektrikli_Fan_Isıtıcı_Lq_501'
      },
      Kumtel_Lx_2832_1500W_Delux_Siyah_Isıtıcı:{
        id: 208,
        name: 'Kumtel Lx-2832 1500W Delux Siyah Isıtıcı',
        brand: 'Scotch Brite',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39155992/39155992-5017b8',
        price: 10,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Kumtel_Lx_2832_1500W_Delux_Siyah_Isıtıcı'
      },
      My_Style_Dekoratif_Led_Isık_Yıldız_Kalp:{
        id: 209,
        name: 'My Style Dekoratif Led Işık Yıldız/Kalp',
        brand: 'Scotch Brite',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119935/39119935-c7c133',
        price: 8,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/My_Style_Dekoratif_Led_Isık_Yıldız_Kalp'
      },
      Urban_Mood_Dekoratif_Işık_Zinciri_8_Mod:{
        id: 210,
        name: 'Urban Mood Dekoratif Işık Zinciri 8 Mod',
        brand: 'Scotch Brite',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119939/39119939-e908d9',
        price: 5,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Urban_Mood_Dekoratif_Işık_Zinciri_8_Mod'
      },
      Urban_Mood_16_Dekoratif_Led_Top_Isık_Zinciri:{
        id: 211,
        name: 'Urban Mood 16 Dekoratif Led Top Işık Zinciri',
        brand: 'Scotch Brite',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119940/39119940-0ceb66',
        price: 8,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Urban_Mood_16_Dekoratif_Led_Top_Isık_Zinciri'
      },
      Mystyle_12li_Led_Isıklı_Foto_Mandal:{
        id: 212,
        name: 'Mystyle 12li Led Işıklı Foto Mandal',
        brand: 'Scotch Brite',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119924/39119924-e84216',
        price: 4,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Mystyle_12li_Led_Isıklı_Foto_Mandal'
      },
      Urban_Mood_Retro_Dekoratif_Led_Işık_Top_4lü:{
        id: 213,
        name: 'Urban Mood Retro Dekoratif Led Işık Top 4lü',
        brand: 'Scotch Brite',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39119938/39119938-b03d61',
        price: 8,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Urban_Mood_Retro_Dekoratif_Led_Işık_Top_4lü'
      },
      General_Home_El_Feneri_Df25:{
        id: 214,
        name: 'General Home El Feneri Df-25',
        brand: 'Scotch Brite',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39109970/39109970-131a6c',
        price: 2,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/General_Home_El_Feneri_Df25'
      },
      Nilson_3lü_Golyat_Topraklı_Fiş_Priz_Siyah:{
        id: 215,
        name: 'Nilson 3lü Golyat - Topraklı Fiş Priz (Siyah)',
        brand: 'Scotch Brite',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/46064715/46064715-9f5ef1',
        price: 1.3,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/Nilson_3lü_Golyat_Topraklı_Fiş_Priz_Siyah'
      },
      glow_worm_3lü_anahtarlı_5M:{
        id: 216,
        name: 'Glow-worm 3lü Anahtarlı  5 M',
        brand: 'Scotch Brite',
        title: 'Hakanskop',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/39100264/glow-worm-3-lu-anahtarli-5-mt-315f11',
        price: 5,
        discount: 0,
        unit: 'Piece',
        path: 'hakanskop/glow_worm_3lü_anahtarlı_5M'
      },
  }
  }
}

export default PRODUCT_DATA;